name: CI
on: workflow_dispatch

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Clean
      run:  rm -rf ./docs
      
    - name: Copy
      run: mv ./build ./docs
      
    - name: Deploy
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git add *
        git commit -m "deploy"
        git push
