name: CI
on: workflow_dispatch

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x, 10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install

    - name: Run build
      run: npm run build

    - name: Moving build to docs directory
      run: cp ./build ./docs  && git commit -m "deploy" && git push
      
    - name: removing ./build folder
      run:  rm -rf ./build
      
    - name: publish a new commit
      run: git add * && git commit -m "deploy" && git push
